EXPERIMENT 9 : Study of Numpy Library

Name : Vivek Reddy

PRN : 25070123135

In [6]:
# Declaration of numpy
import numpy as np

a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

print(a.ndim)
print(b.ndim)

print(a.shape)
print(b.shape)

print(a.dtype)
display(a.dtype)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]
1
2
(7,)
(2, 3)
int64


dtype('int64')

int64


In [7]:
# In-Built functions using Numpy
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [12]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [13]:
print(b * 2)
print(a + 5)

[[ 2  4  6]
 [ 8 10 12]]
[  6  15  25  35  45  55 505]


In [14]:
np.mean(a)

np.float64(93.0)

In [15]:
np.median(a)

np.float64(30.0)

In [16]:
np.max(a)

np.int64(500)

In [17]:
np.min(a)

np.int64(1)

In [18]:
np.sum(a)

np.int64(651)

In [30]:
# Finding determinant and transpose of matrice
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

det = np.linalg.det(x)
print("Determinant of x:",det)

transpose = x.T
print("Transpose of x:\n",transpose)

Determinant of x: 0.0
Transpose of x:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [36]:
# multiplication of two matrice
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[7,8,9],[4,6,5],[3,2,1]])

product = x @ y

print("product of arrays x and y:\n",product)

product of arrays x and y:
 [[ 24  26  22]
 [ 66  74  67]
 [108 122 112]]
